name: 'CI/CD'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'  # Specify the Node.js version you want to use, like 14, 16, etc.

      - name: Install and Run Linter
        run: |
          # This command initializes the package.json file and installs necessary dependencies
          npm init -y
          
          # Install necessary ESLint packages
          npm install eslint eslint-config-standard eslint@^8.0.1 eslint-plugin-import@^2.25.2 eslint-plugin-n@^16.0.0 eslint-plugin-promise@^6.0.0

          # Run ESLint on the JavaScript files
          find ./secondChance-backend -name "*.js" -exec ./node_modules/.bin/eslint -c .eslintrc.js {} +

          echo "Linted all the js files successfully"
